In [2]:
# NumPy package is a powerful tool in python to do numerical computations on arrays faster
# than python lists. It is a package that provide high-performance vector, matrix and higher-dimensional
# data structures for python. It is implemented in C and Fortran so when calculations are vectorized
# (formulated with vectors and matrices), performance is very good.
# NumPy is the fundamental package for scientific computing with Python. It contains among other things:
# a powerful N-dimensional array object
# sophisticated (broadcasting) functions
# tools for integrating C/C++ and Fortran code
# useful linear algebra, Fourier transform, and random number capabilities
# We can not do operations on individual elements of a list in python without using a loop but in Numpy
# we can do operations on whole arrays at once.


In [3]:
import numpy as np

In [4]:
height = np.array([1.9,2,1.5,1.2,1.6])
weight = [90,70,60,55,60]
weight = np.array(weight)
bmi = weight/height**2
print(bmi)
print(type(bmi))

[24.93074792 17.5        26.66666667 38.19444444 23.4375    ]
<class 'numpy.ndarray'>


In [5]:
# NumPy arrays can contain elements of different types, including strings, but these will be converted to
# another type. For example, if we try to create an array with a string and a number, NumPy will interpret
# all elements to be strings.
# Which means we can techically assign diffenerent types of values in numpy arrays but it will convert
# all the values to the same type.
# passing dtype parameter can be used to specify the type of the array elements.

In [6]:
arr = np.array([1,1.04,'5',True])
print(arr) # all the values are converted to string

# passing dtype parameter can be used to specify the type of the array elements.
arr = np.array([1,1.04,'5',True],dtype='float')
print(arr) # all the values are converted to float

['1' '1.04' '5' 'True']
[1.   1.04 5.   1.  ]


In [7]:
# The elements of the array can be accessed by indexing just like list
# There is a cool feature in array. If we want to use a condition to select elements from an array
# we can do it like this
arr = np.array([1,2,3,4,5])
print(arr>3) # prints [False False False  True  True] It is also called the boolean numpy array
print(arr[arr>3]) # prints [4,5]

[False False False  True  True]
[4 5]


In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2D array
print(arr)
print()
print(arr[:2,:2]) # prints [[1 2] [4 5]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]


In [9]:
#shape attribute returns a tuple of integers that indicate the number of elements stored along each dimension
# dtype prints the type of the elements in the array
print(arr.shape , arr.dtype)

(3, 3) int32


In [10]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
# mat = mat + np.array([1,1,1],[1,1,1]) this will cause an error because the shapes are not same
# mat = mat + np.array([1,2]) this will cause an error because the shapes are not same
mat = mat +np.array([1,1,1]) # this will work because the shape is same. output [[2 3 4] [5 6 7] [8 9 10]] 
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(arr)) # prints the mean of the array
print(np.median(arr)) # printts the median of the array
print(np.std(arr)) # prints the standard deviation of the array 
print(np.var(arr)) # prints the variance of the array
print(np.sum(arr)) # prints the sum of the array
print(np.max(arr)) # prints the maximum value of the array
print(np.min(arr)) # prints the minimum value of the array
print(np.argmax(arr)) # prints the index of the maximum value of the array
print(np.argmin(arr)) # prints the index of the minimum value of the array
print(np.exp(arr)) # prints the exponential of the array
print(np.log(arr)) # prints the logarithm of the array
print(np.log10(arr)) # prints the logarithm base 10 of the array


5.0
5.0
2.581988897471611
6.666666666666667
45
9
1
8
0
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Problem: Make two arrays department and budget. Find the budgets of the department 'CSE'. Find the department with less budget than 'CSE'

In [12]:
dept = np.array(['CSE','EEE','IIT','ME','BME','CE'])
budget = np.array([500,500,3000,200,100,700])
cse_bud = dept=='CSE'
print(cse_bud)
print(budget[dept=='CSE']) # Find the budgets of the department 'CSE'
print(dept[budget<budget[dept=='CSE']]) # Find the department with less budget than 'CSE'



[ True False False False False False]
[500]
['ME' 'BME']


In [13]:
# Using boolean operators in numpy arrays
# We can use boolean operators like and, or, not in numpy arrays
# We can use & for and, | for or and ~ for not
# We can use these operators to select elements from an array
# For example, if we want to select elements from an array that are greater than 3 and less than 7

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[(arr>3) & (arr<7)]) # prints [4 5 6]
# There is another way to do this
# & , | , ~ are bitwise operators in python. So we can use np.logical_and() , np.logical_or() , np.logical_not()

print(arr[np.logical_and(arr>3,arr<7)]) # prints [4 5 6]

[4 5 6]
[4 5 6]


In [14]:
print(np.logical_not(arr))

[False False False False False False False False False]


In [24]:
for b in bmi:
    print(b)

np_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print()
for b in np_2d:
    print(b)

for b in np.nditer(np_2d): # prints the elements of the array in a single line
    print(b)

24.930747922437675
17.5
26.666666666666668
38.19444444444444
23.437499999999996

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
